[package]
name = "feathered_common"
version = "0.1.0"
edition = "2021"

[dependencies]
feathered_shipyard.path = "../feathered_shipyard"
raw-window-handle = "0.6.2"
shipyard = "0.7.3"
web-time = "1.1.0"

[target.'cfg(target_arch = "wasm32")'.dependencies]
send_wrapper = "0.6.0"
